import os
import re
from datetime import datetime

from docx import Document
from docx.enum.section import WD_SECTION
from docx.enum.table import WD_CELL_VERTICAL_ALIGNMENT, WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt, RGBColor

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle


OUTPUT_DIR = os.path.join(os.getcwd(), "outputs", "exports")
os.makedirs(OUTPUT_DIR, exist_ok=True)


def clean_text(text: str) -> str:
    if not text:
        return ""

    text = text.replace("**", "")
    text = text.replace("###", "")
    text = text.replace("##", "")
    text = text.replace("#", "")
    text = text.replace("---", "")

    return text.strip()


def split_report_sections(content: str):
    content = clean_text(content)

    lines = [
        line.strip()
        for line in content.splitlines()
        if line.strip()
    ]

    sections = []
    current_title = None
    current_lines = []

    known_titles = {
        "executive summary",
        "executive summary:",
        "tasks completed",
        "tasks completed:",
        "challenges faced",
        "challenges faced:",
        "blockers",
        "blockers:",
        "next action plan",
        "next action plan:",
        "overall status",
        "overall status:",
    }

    for line in lines:
        normalized = line.lower().strip()

        if normalized == "daily progress report":
            continue

        if normalized in known_titles:
            if current_title:
                sections.append((current_title, current_lines))

            title = line.replace(":", "").strip()

            if title.lower() == "blockers":
                title = "Challenges Faced"

            current_title = title
            current_lines = []
        else:
            current_lines.append(line)

    if current_title:
        sections.append((current_title, current_lines))

    if not sections:
        sections.append(("Report Details", lines))

    return sections


def create_professional_docx(content: str, date: str = "", team_name: str = "") -> str:
    filename = f"daily_progress_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
    filepath = os.path.join(OUTPUT_DIR, filename)

    doc = Document()

    section = doc.sections[0]
    section.top_margin = Inches(0.6)
    section.bottom_margin = Inches(0.6)
    section.left_margin = Inches(0.7)
    section.right_margin = Inches(0.7)

    normal_style = doc.styles["Normal"]
    normal_style.font.name = "Calibri"
    normal_style.font.size = Pt(11)

    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title.add_run("DAILY PROGRESS REPORT")
    title_run.bold = True
    title_run.font.size = Pt(20)
    title_run.font.color.rgb = RGBColor(31, 83, 138)

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle_run = subtitle.add_run("Generated by Operations Agent")
    subtitle_run.font.size = Pt(10)
    subtitle_run.font.color.rgb = RGBColor(100, 116, 139)

    doc.add_paragraph("")

    meta_table = doc.add_table(rows=2, cols=2)
    meta_table.alignment = WD_TABLE_ALIGNMENT.CENTER
    meta_table.style = "Table Grid"

    meta_table.cell(0, 0).text = "Date"
    meta_table.cell(0, 1).text = date or "N/A"
    meta_table.cell(1, 0).text = "Team / Project"
    meta_table.cell(1, 1).text = team_name or "N/A"

    for row in meta_table.rows:
        for cell in row.cells:
            cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER

            for paragraph in cell.paragraphs:
                paragraph.paragraph_format.space_after = Pt(2)

                for run in paragraph.runs:
                    run.font.name = "Calibri"
                    run.font.size = Pt(10)

    doc.add_paragraph("")

    sections = split_report_sections(content)

    for heading, lines in sections:
        heading_para = doc.add_paragraph()
        heading_para.paragraph_format.space_before = Pt(10)
        heading_para.paragraph_format.space_after = Pt(5)

        heading_run = heading_para.add_run(heading)
        heading_run.bold = True
        heading_run.font.size = Pt(13)
        heading_run.font.color.rgb = RGBColor(31, 83, 138)

        for line in lines:
            line = clean_text(line)
            clean_line = re.sub(r"^\d+\.\s*", "", line).strip()
            clean_line = re.sub(r"^[-•]\s*", "", clean_line).strip()

            if not clean_line:
                continue

            if re.match(r"^\d+\.", line) or heading.lower() in [
                "tasks completed",
                "challenges faced",
                "next action plan",
            ]:
                para = doc.add_paragraph(style="List Number")
                para.add_run(clean_line)
            else:
                para = doc.add_paragraph()
                para.paragraph_format.line_spacing = 1.15
                para.paragraph_format.space_after = Pt(5)
                para.add_run(clean_line)

    footer = doc.sections[0].footer.paragraphs[0]
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer.add_run("Operations Agent | Professional Report Export")
    footer_run.font.size = Pt(9)
    footer_run.font.color.rgb = RGBColor(100, 116, 139)

    doc.save(filepath)
    return filepath


def create_professional_pdf(content: str, date: str = "", team_name: str = "") -> str:
    filename = f"daily_progress_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = os.path.join(OUTPUT_DIR, filename)

    pdf = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        rightMargin=45,
        leftMargin=45,
        topMargin=45,
        bottomMargin=40,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontSize=20,
        leading=24,
        textColor=colors.HexColor("#1F538A"),
        alignment=1,
        spaceAfter=4,
    )

    subtitle_style = ParagraphStyle(
        "ReportSubtitle",
        parent=styles["Normal"],
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#64748B"),
        alignment=1,
        spaceAfter=18,
    )

    heading_style = ParagraphStyle(
        "ReportHeading",
        parent=styles["Heading2"],
        fontSize=13,
        leading=16,
        textColor=colors.HexColor("#1F538A"),
        spaceBefore=14,
        spaceAfter=8,
    )

    body_style = ParagraphStyle(
        "ReportBody",
        parent=styles["Normal"],
        fontSize=10.5,
        leading=15,
        textColor=colors.HexColor("#1E293B"),
        spaceAfter=6,
    )

    story = []

    story.append(Paragraph("DAILY PROGRESS REPORT", title_style))
    story.append(Paragraph("Generated by Operations Agent", subtitle_style))

    meta_table = Table(
        [
            ["Date", date or "N/A"],
            ["Team / Project", team_name or "N/A"],
        ],
        colWidths=[1.6 * inch, 4.7 * inch],
    )

    meta_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#EEF6FF")),
                ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#1F538A")),
                ("TEXTCOLOR", (1, 0), (1, -1), colors.HexColor("#0F172A")),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("BOX", (0, 0), (-1, -1), 0.8, colors.HexColor("#DBEAFE")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#DBEAFE")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("PADDING", (0, 0), (-1, -1), 9),
            ]
        )
    )

    story.append(meta_table)
    story.append(Spacer(1, 16))

    sections = split_report_sections(content)

    for heading, lines in sections:
        story.append(Paragraph(heading, heading_style))

        for line in lines:
            line = clean_text(line)
            clean_line = re.sub(r"^\d+\.\s*", "", line).strip()
            clean_line = re.sub(r"^[-•]\s*", "", clean_line).strip()

            if not clean_line:
                continue

            if re.match(r"^\d+\.", line) or heading.lower() in [
                "tasks completed",
                "challenges faced",
                "next action plan",
            ]:
                story.append(Paragraph(f"• {clean_line}", body_style))
            else:
                story.append(Paragraph(clean_line, body_style))

    pdf.build(story)
    return filepath