import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../api';
import { forceDownload } from '../utils/download';

function cleanReportText(text = '') {
  return text
    .replaceAll('**', '')
    .replaceAll('###', '')
    .replaceAll('##', '')
    .replaceAll('#', '')
    .replaceAll('---', '')
    .trim();
}

function renderReportContent(text = '') {
  const lines = cleanReportText(text)
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean);

  return lines.map((line, index) => {
    const cleanLine = line.replace(/^\d+\.\s*/, '').trim();

    const headings = [
      'DAILY PROGRESS REPORT',
      'Executive Summary:',
      'Tasks Completed:',
      'Challenges Faced:',
      'Next Action Plan:',
      'Overall Status:',
    ];

    const isHeading = headings.some(
      (heading) => line.toLowerCase() === heading.toLowerCase()
    );

    if (line.toUpperCase() === 'DAILY PROGRESS REPORT') {
      return null;
    }

    if (isHeading) {
      return (
        <h3 className="report-section-title" key={index}>
          {line.replace(':', '')}
        </h3>
      );
    }

    if (/^\d+\./.test(line)) {
      return (
        <li className="report-list-item" key={index}>
          {cleanLine}
        </li>
      );
    }

    return (
      <p className="report-paragraph" key={index}>
        {line}
      </p>
    );
  });
}

function ProfessionalReportView({ report, date, teamName }) {
  return (
    <div className="professional-report">
      <div className="report-top">
        <div>
          <div className="report-icon">📋</div>
        </div>

        <div>
          <h2>Daily Progress Report</h2>
          <p>Generated by Operations Agent</p>
        </div>
      </div>

      <div className="report-meta-grid">
        <div className="report-meta-card">
          <span>📅 Date</span>
          <strong>{date || 'N/A'}</strong>
        </div>

        <div className="report-meta-card">
          <span>👥 Team / Project</span>
          <strong>{teamName || 'N/A'}</strong>
        </div>
      </div>

      <div className="report-body">{renderReportContent(report)}</div>
    </div>
  );
}

function ExportButtons({ id, docType }) {
  const [exporting, setExporting] = useState('');
  const navigate = useNavigate();

  const exportDoc = async (fmt) => {
    setExporting(fmt);

    try {
      const res = await api.post(`/documents/export-${fmt}`, {
        content_id: id,
        doc_type: docType,
        export_format: fmt,
      });

      await forceDownload(res.data.download_url);
    } catch (e) {
      alert('Export failed: ' + (e.response?.data?.detail || e.message));
    } finally {
      setExporting('');
    }
  };

  const goToSendReport = () => {
    navigate(`/send-report?reportId=${id}`);
  };

  return (
    <div
      onClick={(e) => e.stopPropagation()}
      style={{
        display: 'flex',
        gap: '8px',
        marginTop: '14px',
        flexWrap: 'wrap',
      }}
    >
      <button
        className="btn btn-secondary"
        onClick={(e) => {
          e.stopPropagation();
          exportDoc('docx');
        }}
        disabled={!!exporting}
        style={{ fontSize: '13px', padding: '7px 14px' }}
      >
        {exporting === 'docx' ? (
          <span className="spinner" style={{ borderTopColor: 'var(--primary)' }} />
        ) : (
          '📄'
        )}{' '}
        Export DOCX
      </button>

      <button
        className="btn btn-secondary"
        onClick={(e) => {
          e.stopPropagation();
          exportDoc('pdf');
        }}
        disabled={!!exporting}
        style={{ fontSize: '13px', padding: '7px 14px' }}
      >
        {exporting === 'pdf' ? (
          <span className="spinner" style={{ borderTopColor: 'var(--primary)' }} />
        ) : (
          '📕'
        )}{' '}
        Export PDF
      </button>

      <button
        className="btn btn-primary"
        onClick={(e) => {
          e.stopPropagation();
          goToSendReport();
        }}
        disabled={!id}
        style={{ fontSize: '13px', padding: '7px 14px' }}
      >
        📤 Send Report
      </button>
    </div>
  );
}

export default function DailyReport() {
  const today = new Date().toISOString().slice(0, 10);

  const [form, setForm] = useState({
    date: today,
    team_name: '',
    tasks_completed: '',
    blockers: '',
  });

  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [history, setHistory] = useState([]);
  const [selected, setSelected] = useState(null);

  const fetchHistory = () => {
    api
      .get('/report/history')
      .then((r) => setHistory(r.data))
      .catch(console.error);
  };

  useEffect(() => {
    fetchHistory();
  }, []);

  const handle = (e) => {
    setForm({
      ...form,
      [e.target.name]: e.target.value,
    });
  };

  const submit = async (e) => {
    e.preventDefault();

    setLoading(true);
    setError('');
    setResult(null);

    try {
      const res = await api.post('/report/generate', form);
      setResult(res.data);
      fetchHistory();
    } catch (err) {
      setError(err.response?.data?.detail || 'Generation failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="page">
      <h1 className="page-title">📋 Daily Progress Report</h1>

      <div className="daily-report-layout">
        <div className="card">
          <h2 style={{ fontSize: '16px', fontWeight: '700', marginBottom: '18px' }}>
            Generate Daily Report
          </h2>

          {error && <div className="alert alert-error">{error}</div>}

          <form onSubmit={submit}>
            <div className="form-group">
              <label>Date</label>
              <input
                type="date"
                name="date"
                value={form.date}
                onChange={handle}
                required
              />
            </div>

            <div className="form-group">
              <label>Team / Project Name</label>
              <input
                name="team_name"
                value={form.team_name}
                onChange={handle}
                required
                placeholder="e.g. Backend Engineering Team"
              />
            </div>

            <div className="form-group">
              <label>Tasks Completed Today</label>
              <textarea
                name="tasks_completed"
                value={form.tasks_completed}
                onChange={handle}
                required
                placeholder={
                  '- Implemented user authentication\n' +
                  '- Fixed bug in payment module\n' +
                  '- Reviewed 3 PRs'
                }
                style={{ minHeight: '120px' }}
              />
            </div>

            <div className="form-group">
              <label>Blockers / Challenges</label>
              <textarea
                name="blockers"
                value={form.blockers}
                onChange={handle}
                placeholder={'- Waiting for API credentials from DevOps\n- None'}
              />
            </div>

            <button
              type="submit"
              className="btn btn-primary"
              disabled={loading}
              style={{ width: '100%', justifyContent: 'center' }}
            >
              {loading ? (
                <>
                  <span className="spinner" /> Generating…
                </>
              ) : (
                '🤖 Generate Report'
              )}
            </button>
          </form>
        </div>

        <div>
          {result && (
            <div className="card" style={{ marginBottom: '20px' }}>
              <h2
                style={{
                  fontSize: '16px',
                  fontWeight: '700',
                  marginBottom: '12px',
                  color: '#1F538A',
                }}
              >
                ✅ Generated Report
              </h2>

              <ProfessionalReportView
                report={result.generated_report}
                date={result.date || form.date}
                teamName={result.team_name || form.team_name}
              />

              <ExportButtons id={result.id} docType="report" />
            </div>
          )}

          <div className="card">
            <h2 style={{ fontSize: '16px', fontWeight: '700', marginBottom: '14px' }}>
              📚 History
            </h2>

            {history.length === 0 ? (
              <p style={{ color: '#6b7c93', fontSize: '13px' }}>No reports yet</p>
            ) : (
              <div style={{ maxHeight: '360px', overflowY: 'auto' }}>
                {history.map((h) => (
                  <div
                    key={h.id}
                    onClick={() => setSelected(selected?.id === h.id ? null : h)}
                    style={{
                      padding: '10px 12px',
                      borderRadius: '8px',
                      cursor: 'pointer',
                      marginBottom: '6px',
                      background: selected?.id === h.id ? '#eef4ff' : '#f8fafc',
                      border: '1px solid #e2e8f0',
                    }}
                  >
                    <div style={{ fontWeight: '600', fontSize: '13px' }}>
                      {h.team_name}
                    </div>

                    <div style={{ fontSize: '12px', color: '#6b7c93' }}>
                      {h.date} · {new Date(h.created_at).toLocaleString()}
                    </div>

                    {selected?.id === h.id && (
                      <div>
                        <ProfessionalReportView
                          report={h.generated_report}
                          date={h.date}
                          teamName={h.team_name}
                        />

                        <ExportButtons id={h.id} docType="report" />
                      </div>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}