import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../api';
import { forceDownload } from '../utils/download';

function cleanMomText(text = '') {
  return text.replaceAll('**', '').replaceAll('---', '').trim();
}

function renderMomContent(text = '') {
  const lines = cleanMomText(text)
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean);

  return lines.map((line, index) => {
    if (line.startsWith('# ')) {
      return null;
    }

    if (line.startsWith('## ')) {
      return (
        <h3 className="report-section-title" key={index}>
          {line.replace('## ', '')}
        </h3>
      );
    }

    if (line.startsWith('- ') || line.startsWith('* ')) {
      return (
        <li className="report-list-item" key={index}>
          {line.slice(2)}
        </li>
      );
    }

    return (
      <p className="report-paragraph" key={index}>
        {line}
      </p>
    );
  });
}

function ProfessionalMOMView({ mom, title }) {
  return (
    <div className="professional-report">
      <div className="report-top">
        <div className="report-icon">📝</div>
        <div>
          <h2>Minutes of Meeting</h2>
          <p>{title || 'Generated by Operations Agent'}</p>
        </div>
      </div>

      <div className="report-body">{renderMomContent(mom)}</div>
    </div>
  );
}

function ExportButtons({ id }) {
  const [exporting, setExporting] = useState('');
  const navigate = useNavigate();

  const exportDoc = async (fmt) => {
    setExporting(fmt);

    try {
      const res = await api.post(`/documents/export-${fmt}`, {
        content_id: id,
        doc_type: 'meeting',
        export_format: fmt,
      });

      await forceDownload(res.data.download_url);
    } catch (e) {
      alert('Export failed: ' + (e.response?.data?.detail || e.message));
    } finally {
      setExporting('');
    }
  };

  return (
    <div
      onClick={(e) => e.stopPropagation()}
      style={{ display: 'flex', gap: '8px', marginTop: '14px', flexWrap: 'wrap' }}
    >
      <button
        className="btn btn-secondary"
        onClick={(e) => {
          e.stopPropagation();
          exportDoc('docx');
        }}
        disabled={!!exporting}
        style={{ fontSize: '13px', padding: '7px 14px' }}
      >
        {exporting === 'docx' ? (
          <span className="spinner" style={{ borderTopColor: 'var(--primary)' }} />
        ) : (
          '📄'
        )}{' '}
        Export DOCX
      </button>

      <button
        className="btn btn-secondary"
        onClick={(e) => {
          e.stopPropagation();
          exportDoc('pdf');
        }}
        disabled={!!exporting}
        style={{ fontSize: '13px', padding: '7px 14px' }}
      >
        {exporting === 'pdf' ? (
          <span className="spinner" style={{ borderTopColor: 'var(--primary)' }} />
        ) : (
          '📕'
        )}{' '}
        Export PDF
      </button>

      <button
        className="btn btn-primary"
        onClick={(e) => {
          e.stopPropagation();
          navigate(`/send-mom?meetingId=${id}`);
        }}
        disabled={!id}
        style={{ fontSize: '13px', padding: '7px 14px' }}
      >
        📤 Send MOM
      </button>
    </div>
  );
}

export default function MeetingMOM() {
  const [form, setForm] = useState({
    meeting_title: '',
    attendees: '',
    raw_notes: '',
  });

  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [history, setHistory] = useState([]);
  const [selected, setSelected] = useState(null);

  const fetchHistory = () => {
    api
      .get('/meeting/history')
      .then((r) => setHistory(r.data))
      .catch(console.error);
  };

  useEffect(() => {
    fetchHistory();
  }, []);

  const handle = (e) => {
    setForm({
      ...form,
      [e.target.name]: e.target.value,
    });
  };

  const submit = async (e) => {
    e.preventDefault();

    setLoading(true);
    setError('');
    setResult(null);

    try {
      const res = await api.post('/meeting/generate-mom', form);
      setResult(res.data);
      fetchHistory();
    } catch (err) {
      setError(err.response?.data?.detail || 'Generation failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="page">
      <h1 className="page-title">📝 Meeting MOM Generator</h1>

      <div className="daily-report-layout">
        <div className="card">
          <h2 style={{ fontSize: '16px', fontWeight: '700', marginBottom: '18px' }}>
            Generate Minutes of Meeting
          </h2>

          {error && <div className="alert alert-error">{error}</div>}

          <form onSubmit={submit}>
            <div className="form-group">
              <label>Meeting Title</label>
              <input
                name="meeting_title"
                value={form.meeting_title}
                onChange={handle}
                required
                placeholder="e.g. Q4 Planning Meeting"
              />
            </div>

            <div className="form-group">
              <label>Attendees</label>
              <input
                name="attendees"
                value={form.attendees}
                onChange={handle}
                required
                placeholder="John (PM), Sarah (Dev), Mike (QA)"
              />
            </div>

            <div className="form-group">
              <label>Raw Meeting Notes</label>
              <textarea
                name="raw_notes"
                value={form.raw_notes}
                onChange={handle}
                required
                style={{ minHeight: '160px' }}
                placeholder={
                  'Paste your raw notes here...\n' +
                  '- Discussed Q4 roadmap\n' +
                  '- John to deliver feature X by Friday\n' +
                  '- Budget approved for $5k tools'
                }
              />
            </div>

            <button
              type="submit"
              className="btn btn-primary"
              disabled={loading}
              style={{ width: '100%', justifyContent: 'center' }}
            >
              {loading ? (
                <>
                  <span className="spinner" /> Generating MOM…
                </>
              ) : (
                '🤖 Generate MOM'
              )}
            </button>
          </form>
        </div>

        <div>
          {result && (
            <div className="card" style={{ marginBottom: '20px' }}>
              <h2 style={{ fontSize: '16px', fontWeight: '700', marginBottom: '12px', color: '#1F538A' }}>
                ✅ Generated MOM
              </h2>

              <ProfessionalMOMView mom={result.generated_mom} title={result.meeting_title} />

              <ExportButtons id={result.id} />
            </div>
          )}

          <div className="card">
            <h2 style={{ fontSize: '16px', fontWeight: '700', marginBottom: '14px' }}>
              📚 History
            </h2>

            {history.length === 0 ? (
              <p style={{ color: '#6b7c93', fontSize: '13px' }}>No MOMs yet</p>
            ) : (
              <div style={{ maxHeight: '360px', overflowY: 'auto' }}>
                {history.map((h) => (
                  <div
                    key={h.id}
                    onClick={() => setSelected(selected?.id === h.id ? null : h)}
                    style={{
                      padding: '10px 12px',
                      borderRadius: '8px',
                      cursor: 'pointer',
                      marginBottom: '6px',
                      background: selected?.id === h.id ? '#eef4ff' : '#f8fafc',
                      border: '1px solid #e2e8f0',
                    }}
                  >
                    <div style={{ fontWeight: '600', fontSize: '13px' }}>
                      {h.meeting_title}
                    </div>

                    <div style={{ fontSize: '12px', color: '#6b7c93' }}>
                      {new Date(h.created_at).toLocaleString()}
                    </div>

                    {selected?.id === h.id && (
                      <div style={{ marginTop: '10px' }}>
                        <ProfessionalMOMView mom={h.generated_mom} title={h.meeting_title} />
                        <ExportButtons id={h.id} />
                      </div>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}